### ISSUE TITLE
Missing styles for working location

### ISSUE THREAD

**Issue by EladBezalel** [fabian-kho/arc_boosts#2]
<img width="455" alt="image" src="https://user-images.githubusercontent.com/6004537/227147425-e1fa991c-a657-45c2-b4cd-b5c54a4e1d01.png">

fixed it with adding
```css
[data-is-pill], [data-is-pill] ~ *, .E4zakf {
  background-color: var(--primary)!important;
}
```

<img width="452" alt="image" src="https://user-images.githubusercontent.com/6004537/227147695-78769983-826b-4b74-a31e-ff3ade476f63.png">
