### ISSUE TITLE
Add support for sidebar as well

### ISSUE THREAD

**Issue by abhi21git** [fabian-kho/arc_boosts#6]
Currently the side bar is white, add below code to fix it
``` CSS
.akJTWe, .TKMrfe {
    background-color: var(--mdc-theme-surface) !important;
}
```
Before:
![image](https://user-images.githubusercontent.com/42537316/236134528-8846614b-3c05-4e51-a6c9-d396b3465717.png)

After:
![image](https://user-images.githubusercontent.com/42537316/236134629-8e54145b-250b-44a9-80c5-4cc16e208f0b.png)
